version: v1

sources:
  webhook-main:
    type: webhook
    config:
      path: /webhook/main
      method: POST

  scraper:
    type: http-poller 
    config:
      url: https://7f5211bc3c2643b38f3388294423d7c9.api.mockbin.io/
      method: GET
      headers:
        Accept: application/json
      body: ""
      interval: 10s



sinks:
  stdout-log:
    type: stdout
    config: {}

  file-logger:
    type: file
    config:
      path: ./logs/main/
      append: true

  notify-service:
    type: http
    config:
      method: POST
      url: https://1fe38de2b6b840d297c5e95d515a56e6.api.mockbin.io/
      headers:
        X-Auth-Token: abc123
