version: v1

sources:
  webhook-main:
    type: webhook
    config:
      path: /webhook/main
      method: POST
      schema: schemas/main.json

sinks:
  stdout-log:
    type: stdout
    config: {}

  file-logger:
    type: file
    config:
      path: ./logs/main/

  notify-service:
    type: webhook
    config:
      method: POST
      url: http://internal.service.local/notify
      headers:
        X-Auth-Token: abc123
