version: v1

sources:
  webhook-main:
    type: webhook
    config:
      path: /webhook/main
      method: POST

  scrapper:
    type: http-poller 
    config:
      url: https://jsonplaceholder.typicode.com/posts/1
      method: GET
      headers:
        Accept: application/json
      body: ""
      interval: 10s



sinks:
  stdout-log:
    type: stdout
    config: {}

  file-logger:
    type: file
    config:
      path: ./logs/main/
      append: true

  notify-service:
    type: http
    config:
      method: POST
      url: http://internal.service.local/notify
      headers:
        X-Auth-Token: abc123
