version: v1

routes:
  - name: main_fanout
    source: webhook-main
    sinks:
      - stdout-log
      - file-logger
      - notify-service

  - name: scraper_eval
    source: scraper
    rules:
      - condition: event.status == "warning" && event.usage > 80
        sinks:
          - notify-service

      - condition: event.warning == "ok"
        sinks:
          - stdout-log

      - condition: # all other cases
        sinks:
          - file-logger