version: v1

routes:
  - name: main_fanout
    source: webhook-main
    sinks:
      - stdout-log
      - file-logger
      - notify-service

  - name: scrapper_fanout
    source: scrapper
    sinks:
      - stdout-log
      - file-logger 